models:
    - claude-3-5-sonnet-20240620:
        model_name: claude-3-5-sonnet-20240620
        base_url: https://api.dwyu.top/v1
    # - claude-3-5-sonnet-20241022:
    #     model_name: claude-3-5-sonnet-20241022
    #     base_url: https://api.dwyu.top/v1
    - claude-3-5-haiku-20241022:
        model_name: claude-3-5-haiku-20241022
        base_url: https://api.dwyu.top/v1
        
