models:
    - deepseek-r1-distill-qwen-32b:
        model_name: deepseek-r1-distill-qwen-32b
        base_url: http://100.107.154.21:12000/v1
    - qwen2-vl-7b-instruct:
        model_name: qwen2-vl-7b-instruct
        base_url: http://100.107.154.21:8000/v1
    - molmo-7b-d-0924:
        model_name: molmo-7b-d-0924
        base_url: http://100.107.154.21:9000/v1
